ocr_models = "/mnt/var/models/"
openai_model = "gpt-4"
deepseek_model = "deepseek-chat"
grok_model = ""

deepseek = "https://api.deepseek.com"
gpt = "https://api.openai.com/v1"
grok = ""

ollama_url = "http://localhost"
ollama_port = 11434
ollama_model = "deepseek-r1:32b"

voice = "VR6AewLTigWG4xSOukaG"

# The location of Anki database
anki = "~/.var/app/net.ankiweb.Anki/data/Anki2/User 1/collection.anki2"

[api_keys]
openai = ""
deepl = ""
elevenlabs = ""
grok = ""
deepseek = ""

[window]
w = 850
h = 800
# Language, look at labels for supported values
lang = "eng"
font = "Source Han Serif CN"
# Theme, available values are:
# 	Light (default), Dark, Dracula, Nord, Solarized Light, Solarized Dark, Gruvbox Light, 
#       Gruvbox Dark, Catppuccin Latte, Catppuccin Frappe, Catppuccin Macchiato, 
#       Catppuccin Mocha, Tokyo Night, Tokyo Night Storm, Tokyo Night Light, Kanagawa Wave, 
#       Kanagawa Dragon, Kanagawa Lotus, Moonfly, Nightfly, Oxocarbon, Ferra
theme = "Tokyo Night"
padding = 10
# Font size
font_size = 18.0

default = "-"
